export const white = 'white';
export const black = 'black';
export const red = 'red';
export const green = 'green';
export const accentColor = 'dodgerblue';
export const primaryColor = 'rgb(212, 0, 0)';
export const secondaryColor = 'lightgrey';
export const secondaryColorDarker = '#8f8f8f';
export const secondaryColorLighter = '#edf1f7';
